language: node_js
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "node"
  - "6"
  - "4"
install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm install
